# Generated by Django 4.1.3 on 2026-03-27 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0046_alter_bankaccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 2, 43, 34, 668392)),
        ),
    ]
