# Generated by Django 4.1.3 on 2026-03-27 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0037_alter_historialobject_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 2, 43, 34, 670097)),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 2, 43, 34, 670457)),
        ),
    ]
