# Generated by Django 4.1.3 on 2026-03-28 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_alter_historialobject_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 21, 51, 30, 184813)),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 21, 51, 30, 185193)),
        ),
    ]
