# Generated by Django 4.1.3 on 2026-03-29 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_alter_historialobject_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialobject',
            name='account_participant_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialobject',
            name='user_participant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialobjectreceived',
            name='account_participant_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialobjectreceived',
            name='user_participant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 29, 1, 48, 5, 277785)),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 29, 1, 48, 5, 278167)),
        ),
    ]
