# Generated by Django 4.1.3 on 2026-03-29 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_historialobject_account_participant_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 29, 2, 9, 5, 385340)),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 29, 2, 9, 5, 385731)),
        ),
    ]
